apiVersion: v1
kind: Service
metadata:
    labels:
        run: nodejs
    name: nodejs
spec:
    ports:
    - name default
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      run: nodejs
status:
    loadBalancer: {}

